### ISSUE TITLE
JeVois camera is not recognized in ArchLinux

### ISSUE THREAD

**Issue by goekce** [jevois/jevois-inventor#6]
I am both in _video_ and _uucp_ groups. I can see that two /dev/ttyACM* and two /dev/video* devices are present. _guvcview_ can access the camera. Still jevois-inventor does not show the camera.

I would like to debug the issue. Does jevois-inventor have any debug output that can be activated by the user?

**Comment by jevois** [comment]
yes, see the macro DEBU() in Config.H

To activate it, uncomment the non-trivial variant and comment-out the trivial one.

To use it, you will need to recompile the inventor. First, download the latest Qt directly from the Qt web site. Then in the inventor folder, ~/Qt/5.xx.xx/.../bin/qmake

and finally make

**Comment by goekce** [comment]
I noticed that on ArchLinux the package gst-plugins-bad is a dependence because
/usr/lib/qt/plugins/mediaservice/libgstcamerabin.so requires
libgstphotography-1.0.so.0

I found out this by running::

  QT_DEBUG_PLUGINS=1 jevois-inventor

If this dependency is missing, then jevois-inventor cannot find any cameras.
