### ISSUE TITLE
Deb package for Ubuntu 22.04LTS

### ISSUE THREAD

**Issue by Fabien-B** [jevois/jevois-inventor#8]
Hello,
Can you release a deb package for Ubuntu 22.04 LTS ?
If I try to use the 20.04 deb, its misses the `libicui18n.so.66` dynamic library.
Since 22.04 is an LTS, it would be nice to support it!

An other option would be to release an AppImage.

(not that this is the same problem as #2)

**Comment by jevois** [comment]
Hi

thanks for your interest in jevois!

We recompiled it for 22.04 but I do not have a good way to test it, it
seems to run on a virtualbox but I am having trouble forwarding the USB
ports to my virtual machine. Can you please try this:

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys DD24C027

sudo add-apt-repository "deb https://jevois.usc.edu/apt jammy main"

sudo apt purge modemmanager

sudo apt install jevois-inventor

sudo usermod -aG dialout $USER # need to reboot to take effect

sudo usermod -aG video $USER # need to reboot to take effect

then reboot, login, connect the camera and start jevois-inventor

and let me know if it works?

best

  -- laurent

**Comment by Fabien-B** [comment]
Tested, it works!
